### ISSUE TITLE
startRecording() called on an uninitialzed AudioRecord.

### ISSUE THREAD

**Issue by zohurul** [DeanThomson/android-udp-audio-chat#3]
I get this error message while received call.

java.lang.illegalStateException: startRecording() called on an uninitialized AudioRecord.
at android.media.AudioRecord.startRecording(AudioRecord.java:895) at packagename.AudioCall $1.run(AudioCall.java:76) at java.lang.Thread.run(Thread.java:818)

**Comment by AndreaMartinLomas** [comment]
Hello:

I have the same error as you. Did you get it fixed?

**Comment by Amirhf1** [comment]
2020-05-10 17:35:55.299 22314-22663/com.amirhf.bikechat E/AndroidRuntime: FATAL EXCEPTION: Thread-16
    Process: com.amirhf.bikechat, PID: 22314
    java.lang.IllegalStateException: startRecording() called on an uninitialized AudioRecord.
        at android.media.AudioRecord.startRecording(AudioRecord.java:993)
        at com.amirhf.bikechat.AudioCall$1.run(AudioCall.java:73)
        at java.lang.Thread.run(Thread.java:764)

**Comment by mrez9** [comment]
make sure add this line in AndroidManifest.xml 
`<uses-permission android:name="android.permission.RECORD_AUDIO"/>`
